FRONTENDSCHOOL7/final-02-doublechaek

src/Pages/TestPage.jsx, src/components/Common/Modal/Modal.jsx, src/components/Common/Modal/ModalStyle.jsx, src/components/Common/Toast/Toast.jsx
<br>
모달, 토스트 기능 구현 추가 
<br><br>
모달 백드롭과 모달창, 토스트 기능 구현 
<br><br>
<br><br>
- Close #9
<br><br>
=> feat: 모달, 토스트 기능 구현 #9

src/Hooks/useToast.js, src/Pages/TestPage.jsx, src/atoms/modal.js, src/components/Common/Toast/Toast.jsx
<br>
모달 atom, 토스트 custom hook 구현
<br><br>
토스트 커스텀 훅 추가
모달 atom 추가 
<br><br>
<br><br>
- Close #11 
<br><br>
=> feat: 모달 atom, 토스트 custom hook 구현 #11

src/Styles/GlobalStyle.js, src/components/Common/Textarea/Textarea.jsx, src/components/Common/Textarea/TextareaStyle.jsx, src/components/EditPhrase/EditPhrase.jsx, src/components/EditPhrase/EditPhraseStyle.jsx
<br>
글 작성 컴포넌트 구현
<br><br>
텍스트에어리어와 에딧 컴포넌트 구현 
<br><br>
<br><br>
- Close #22 
<br><br>
=> feat: 글 작성 컴포넌트 구현 #22

src/Styles/GlobalStyle.js, src/components/Common/Textarea/Textarea.jsx, src/components/Common/Textarea/TextareaStyle.jsx, src/components/EditPhrase/EditPhraseStyle.jsx
<br>
텍스트 편집 컴포넌트 구현
<br><br>
- 텍스트에이리어 줄바꿈 시 자동 높이 조절 기능 수정 
- 제목, 저자, 내용을 작성할 수 있는 글귀 작성 컴포넌트 구현 
<br><br>
<br><br>
- Close #26 
<br><br>
=> feat: 텍스트 편집 컴포넌트 구현

src/components/EditPhrase/EditPhrase.jsx
<br>
글귀 편집 컴포넌트 수정
<br><br>
글귀 편집 컴포넌트 수정
<br><br>
<br><br>
- Close #39 
<br><br>
=> fix: 글귀 편집 컴포넌트 수정 #39

src/API/phrase.js, src/App.js, src/Pages/Phrase/PhraseList.jsx, src/Pages/Phrase/PhraseWrite.jsx
<br>
글귀 목록 페이지 구현
<br><br>
글귀 목록 페이지, 글귀 작성 페이지 구현, app.js 리액트 쿼리 적용 
<br><br>
<br><br>
- Close #40
<br><br>
=> feat: 글귀 목록 페이지 구현 #40

package-lock.json, package.json, src/Pages/Book/BookDetailPage.jsx, src/Styles/FeatureStyle.js, src/components/Book/BookDetail.jsx, src/components/Book/BookList.jsx, src/components/BookSlide/BookSlide.jsx, src/components/BookSlide/BookSlideItem.jsx, src/components/Common/Button/StarButton.jsx, src/components/Common/NavBar/NabBarStyle.jsx, src/components/Common/Toast/CustomToast.jsx, src/components/Common/TopBar.jsx, src/components/Common/TopBarBtn.jsx
<br>
토스트 팝업 추가했습니다!!  경로 :  Common > Toast > CustomToast.jsx
<br><br>
<br><br>
<br><br>
<br><br>
=> style :  별 모양 저장 버튼 추가 , 팝업 추가 

src/components/Common/Textarea/Textarea.jsx, src/components/Common/Textarea/TextareaStyle.jsx
<br>
텍스트에어리어 자동길이 조절 수정
<br><br>
텍스트에어리어 자동길이 조절 수정 및 텍스트에어리어 placeholder prop 전달 
<br><br>
<br><br>
- Close #54 
<br><br>
=> fix: 텍스트에어리어 자동길이 조절 수정

src/Pages/MainPage.jsx, src/Pages/Phrase/PhraseUpdate.jsx, src/Pages/Phrase/PhraseUpload.jsx, src/Pages/SearchPage.jsx, src/components/Common/Topbar/Topbar.jsx
<br>
상단바 컴포넌트 수정
<br><br>
상단바 컴포넌트 폴더 생성 후 상단부 컴포넌트 새로 생성
메인, 검색, 글귀 목록, 글귀 작성, 글귀 수정 페이지에 상단바 적용 
<br><br>
<br><br>
- Close #69 
<br><br>
=> fix: 상단바 컴포넌트 수정 #69

src/Styles/GlobalStyle.js, src/components/Common/NavBar/NabBarStyle.jsx
<br>
글로벌 스타일, navbar 스타일 변경
<br><br>
글로벌 스타일 폰트 색상 변경 및 z-index 조절 
<br><br>
<br><br>
- Close #73 
<br><br>
=> fix: 글로벌 스타일, navbar 스타일 변경 #73

src/API/post1.js, src/App.js, src/Hooks/useTimeSince.js, src/Pages/Post/PostMain.jsx, src/Recoil/Modal.js, src/components/Post/Post.jsx
<br>
리뷰 전체보기 페이지 구현
<br><br>
리뷰(포스트) 컴포넌트 구현, 리뷰 전체보기 페이지 구현, 타임포맷 커스텀 훅 구현
<br><br>
<br><br>
<!-- ex) Close #75 
<br><br>
=> [feat] 리뷰 전체보기 페이지 구현, 타임포맷 커스텀 훅 구현 #75

src/Hooks/useCustomToast.js, src/components/Common/Modal/Modal.jsx, src/components/Common/Modal/ModalStyle.jsx
<br>
모달 컴포넌트 수정
<br><br>
모달 스타일드 컴포넌트 태그 변경 및 모달 아톰 수정 
<br><br>
<br><br>
- Close #83 
<br><br>
=> fix: 모달 컴포넌트 수정  #83

src/App.js, src/Pages/LoginPage.jsx, src/Pages/SplashPage.jsx
<br>
<br><br>
<br><br>
<br><br>
<br><br>
=> style: splash, login input 수정 PR등록

src/assets/images/icon/show-more-x.svg, src/components/Common/Button/ButtonStyle.jsx, src/components/Common/NavBar/NavBarStyle.jsx
<br>
공통 컴포넌트 수정
<br><br>
버튼, 하단바 스타일 수정 및 더보기 아이콘 추가 
<br><br>
<br><br>
- Close #98
<br><br>
=> style: 공통 컴포넌트 버튼, 하단바 수정 및 아이콘 추가 #98

src/API/Comment.js, src/Recoil/CommentText.js, src/components/Comment/CommentItem.jsx, src/components/Comment/CommentUpload.jsx, src/components/Comment/Comments.jsx
<br>
댓글 컴포넌트 구현
<br><br>
댓글 목록, 등록, 삭제, 신고 api 구현
댓글 목록, 업로드 컴포넌트 구현
댓글 스타일드 적용 
<br><br>
<br><br>
<!-- ex) Close #102 
<br><br>
=> feat: 댓글 컴포넌트 구현

src/API/Comment.js, src/Hooks/useCustomToast.js, src/Pages/Phrase/PhraseEdit.jsx, src/Pages/Phrase/PhraseList.jsx, src/Pages/Phrase/PhraseUpdate.jsx, src/Pages/Phrase/PhraseUpload.jsx, src/Pages/Post/PostDetailPage.jsx, src/Pages/Post/PostEditPage.jsx, src/Pages/Post/PostPage.jsx, src/components/Comment/CommentItem.jsx, src/components/Comment/CommentUpload.jsx, src/components/Post/Post.jsx
<br>
토스트 커스텀 훅 수정 및 경로 수정
<br><br>
토스트 훅의 export, import 수정으로 코드 삭제 및 success 토스트 생성 
<br><br>
<br><br>
- Close #104 
<br><br>
=> fix: 토스트 커스텀 훅 수정 및 경로 수정 #104

src/components/Comment/CommentUpload.jsx
<br>
댓글텍스트에어리어 스크롤바 숨김
<br><br>
<br><br>
<br><br>
- Close #109 
<br><br>
=> style: 댓글텍스트에어리어 스크롤바 숨김

src/API/Comment.js, src/Recoil/CommnetCount.js, src/components/Comment/CommentItem.jsx, src/components/Comment/CommentUpload.jsx, src/components/Comment/Comments.jsx
<br>
댓글 수 최신 상태로 반영
<br><br>
댓글이 등록되거나 삭제 됐을 때 피드 상세페이지에 댓글 수를 최신 상태로 반영하고
상세페이지에 댓글 수를 게시글 목록에도 보이게 recoil 수정 
<br><br>
<br><br>
- Close #113 
<br><br>
=> fix: 댓글 수 최신 상태로 반영 #113

src/components/Post/Post.jsx, src/components/Post/PostDetail.jsx
<br>
피드 목록 댓글 수 추가 
<br><br>
피드 목록에 댓글 수 반영하고 스타일 변경 
<br><br>
<br><br>
- Close #115 
<br><br>
=> fix: 피드 목록 댓글 수 추가 및 스타일 변경 #115

src/Pages/SetMyInfo.jsx, src/components/Category.jsx
<br>
<br><br>
<br><br>
<br><br>
<br><br>
=> Fix: setMyProfile PR등록

src/Pages/SetMyInfo.jsx
<br>
<br><br>
<br><br>
<br><br>
<br><br>
=> style: PR등록

src/components/Comment/CommentItem.jsx, src/components/Comment/CommentUpload.jsx
<br>
댓글 더보기 모달 구현
<br><br>
댓글에서 더보기를 눌렀을 때 사용자와 작성자가 같으면 삭제 모달을 나오고 
다르면 신고 모달을 나오도록 구현 
<br><br>
<br><br>
- Close #122 
<br><br>
=> fix: 댓글 더보기 모달 구현

src/components/Common/HamSideBar/HamSideYesLogin.jsx
<br>
사이드바 위치 조정
<br><br>
<br><br>
<br><br>
- Close #124 
<br><br>
=> style: 사이드바 위치 조정 #124

src/Pages/LoginPage.jsx, src/components/Common/HamSideBar/HamSideYesLogin.jsx
<br>
<br><br>
<br><br>
<br><br>
<br><br>
=> fix: 로그아웃, 로그인했을 때 메인페이지 새로고침(토큰 값 변경될때 랜더링) PR등록

src/Recoil/FeedView.js, src/components/Common/Button/ButtonStyle.jsx, src/components/Common/Button/ViewToggleButton.jsx, src/components/Common/NavBar/NavBar.jsx
<br>
공통 컴포넌트 수정 
<br><br>
제일 작은 버튼 스타일 min-height 추가 
피드 뷰 버튼 컴포넌트 생성 및 피드 뷰 아톰 생성 
네비게이션바 프로필 경로 수정 
<br><br>
<br><br>
- Close #143 
<br><br>
=> fix: 공통 컴포넌트 수정 및 피드 뷰 아톰 구현 #143

src/App.js, src/Pages/ProfilePage.jsx, src/components/Post/PostDetail.jsx
<br>
프로필 경로 수정
<br><br>
app.js 프로필 라우터 수정 
<br><br>
<br><br>
- Close #147 
<br><br>
=> fix: 프로필 라우터 수정 

src/API/Post.js, src/Pages/Post/PostMain.jsx, src/assets/Skeleton/PostDetailSkeleton.jsx, src/assets/Skeleton/PostSkeleton.jsx, src/components/Banner/BannerData.js, src/components/Common/HamSideBar/HamSideYesLogin.jsx
<br>
<br><br>
<br><br>
<br><br>
<br><br>
=> feat: 스켈레톤 추가 및 경로 변경

src/Pages/Post/PostMain.jsx, src/components/Post/PostGallery.jsx, src/components/Post/PostItem.jsx, src/components/Post/UserPost.jsx
<br>
post._id 를 post.id로 바꿨습니다 
<br><br>
<br><br>
<br><br>
<br><br>
=> fix:  post 경로 수정

src/App.js, src/Pages/SignupPage.jsx, src/components/Common/HamSideBar/HamSideNoLogin.jsx
<br>
<br><br>
<br><br>
<br><br>
<br><br>
=> fix: signup PR 등록

src/Pages/Post/PostDetailPage.jsx, src/components/Post/PostItem.jsx
<br>
피드 수정페이지 수정
<br><br>
피드 상세페이지에서 수정할 때 책 데이터가 지워져서 수정되는 문제 해결 
상세페이지 api 호출 후 초기화 코드로 인해 수정할 때 
데이터가 초기화된 상태로 진행된 것이 문제 원인
<br><br>
<br><br>
- Close #153 
<br><br>
=> fix: 피드 수정페이지 수정  #153

src/Pages/SetMyInfo.jsx, src/components/Category.jsx
<br>
<br><br>
<br><br>
<br><br>
<br><br>
=> fix: category PR등록

src/Pages/ProfilePage.jsx, src/components/Common/Button/ButtonStyle.jsx
<br>
버튼 스타일 수정 및 프로필 하단바 atom 추가
<br><br>
<br><br>
<br><br>
- Close #160 
<br><br>
=> style: 버튼 스타일 수정 및 프로필 하단바 atom 추가 #160 

src/components/Common/Modal/Modal.jsx
<br>
모달 경로 수정
<br><br>
<br><br>
<br><br>
<br><br>
=> fix: 모달 경로 수정
